"""Initial migration

Revision ID: a509074fca30
Revises: 
Create Date: 2026-02-19 17:07:33.510408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a509074fca30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_structuring_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('current_structure', sa.JSON(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_structuring_sessions_id'), 'jd_structuring_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_jd_structuring_sessions_jd_id'), 'jd_structuring_sessions', ['jd_id'], unique=False)
    op.create_index(op.f('ix_jd_structuring_sessions_session_id'), 'jd_structuring_sessions', ['session_id'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('skills_weightage', sa.JSON(), nullable=True),
    sa.Column('is_structured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_session_id'), 'job_descriptions', ['session_id'], unique=False)
    op.create_table('matching_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('detailed_analysis', sa.JSON(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_results_id'), 'matching_results', ['id'], unique=False)
    op.create_index(op.f('ix_matching_results_session_id'), 'matching_results', ['session_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('skills_extracted', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_session_id'), 'resumes', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('jd_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('jd_name', sa.String(length=500), nullable=False),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('skills_weightage', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_library_id'), 'jd_library', ['id'], unique=False)
    op.create_index(op.f('ix_jd_library_user_id'), 'jd_library', ['user_id'], unique=False)
    op.create_table('matching_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('total_resumes', sa.Integer(), nullable=True),
    sa.Column('successful_matches', sa.Integer(), nullable=True),
    sa.Column('top_candidate_name', sa.String(length=255), nullable=True),
    sa.Column('top_candidate_score', sa.Float(), nullable=True),
    sa.Column('matching_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_history_id'), 'matching_history', ['id'], unique=False)
    op.create_index(op.f('ix_matching_history_session_id'), 'matching_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_matching_history_user_id'), 'matching_history', ['user_id'], unique=False)
    op.create_table('jd_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_library_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resumes_processed', sa.Integer(), nullable=True),
    sa.Column('top_candidate_score', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jd_library_id'], ['jd_library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_usage_history_id'), 'jd_usage_history', ['id'], unique=False)
    op.create_index(op.f('ix_jd_usage_history_jd_library_id'), 'jd_usage_history', ['jd_library_id'], unique=False)
    op.create_index(op.f('ix_jd_usage_history_session_id'), 'jd_usage_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jd_usage_history_session_id'), table_name='jd_usage_history')
    op.drop_index(op.f('ix_jd_usage_history_jd_library_id'), table_name='jd_usage_history')
    op.drop_index(op.f('ix_jd_usage_history_id'), table_name='jd_usage_history')
    op.drop_table('jd_usage_history')
    op.drop_index(op.f('ix_matching_history_user_id'), table_name='matching_history')
    op.drop_index(op.f('ix_matching_history_session_id'), table_name='matching_history')
    op.drop_index(op.f('ix_matching_history_id'), table_name='matching_history')
    op.drop_table('matching_history')
    op.drop_index(op.f('ix_jd_library_user_id'), table_name='jd_library')
    op.drop_index(op.f('ix_jd_library_id'), table_name='jd_library')
    op.drop_table('jd_library')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resumes_session_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_matching_results_session_id'), table_name='matching_results')
    op.drop_index(op.f('ix_matching_results_id'), table_name='matching_results')
    op.drop_table('matching_results')
    op.drop_index(op.f('ix_job_descriptions_session_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_jd_structuring_sessions_session_id'), table_name='jd_structuring_sessions')
    op.drop_index(op.f('ix_jd_structuring_sessions_jd_id'), table_name='jd_structuring_sessions')
    op.drop_index(op.f('ix_jd_structuring_sessions_id'), table_name='jd_structuring_sessions')
    op.drop_table('jd_structuring_sessions')
    # ### end Alembic commands ###
